use crate::{AccountId, AssetId};

#[derive(Debug)]
pub enum SettlementError {
    TooManyAccounts,
    TooManyOrders,
    TooManyAssets,
    TooManyMarkets,
    DuplicateAccount,
    DuplicateBalance,
    DuplicateAsset,
    DuplicateMarket,
    DuplicateSequence,
    UnknownAccount,
    UnknownAsset,
    UnknownMarket,
    MissingFeeRecipient,
    ZeroAssetScale,
    ZeroBalance,
    ZeroPrice,
    ZeroQuantity,
    IdenticalMarketAssets,
    InvalidFee,
    InvalidNonce,
    NonceOverflow,
    OldStateRootMismatch,
    SelfTrade,
    InsufficientBalance {
        account: AccountId,
        asset: AssetId,
        available: u128,
        required: u128,
    },
    ArithmeticOverflow,
    TradeValueRoundsToZero,
}
