use crate::{AccountId, AssetId};

#[derive(Debug)]
pub enum SettlementError {
    TooManyAccounts,
    TooManyOrders,
    TooManyAssets,
    TooManyMarkets,
    DuplicateAccount,
    DuplicateBalance,
    DuplicateAsset,
    DuplicateMarket,
    DuplicateMarketOrderBook,
    DuplicateOrderIndex,
    DuplicateSequence,
    UnknownAccount,
    UnknownAsset,
    UnknownMarket,
    MissingFeeRecipient,
    MissingOrderIndex,
    EmptyOrderBook,
    ZeroAssetScale,
    ZeroBalance,
    ZeroPrice,
    ZeroQuantity,
    IdenticalMarketAssets,
    InvalidFee,
    InvalidNonce,
    InvalidOrderIndex,
    OrderBookMarketMismatch,
    OrderBookSideMismatch,
    UnsortedAccounts,
    UnsortedAssets,
    UnsortedBalances,
    UnsortedMarkets,
    UnsortedMarketOrderBooks,
    UnsortedOrderBook,
    NonceOverflow,
    OldStateRootMismatch,
    InvalidStateMultiproof,
    SelfTrade,
    InsufficientBalance {
        account: AccountId,
        asset: AssetId,
        available: u128,
        required: u128,
    },
    ArithmeticOverflow,
    TradeValueRoundsToZero,
    AssetConservationViolation,
}
